/**
 * Created by ZL on 2018/1/29.
 */

export const WINTER_CAMP = {
    WINTER_CAMP_SELECTED_TEXTBOOK: 'WINTER_CAMP_SELECTED_TEXTBOOK',
    WINTER_CAMP_SELECTED_GRADE: 'WINTER_CAMP_SELECTED_GRADE',
    CHANGE_WINTER_CAMP_SELECTED_GRADE_FLAG: 'CHANGE_WINTER_CAMP_SELECTED_GRADE_FLAG',

    FETCH_WINTER_CAMP_ALL_COURSES_START:'FETCH_WINTER_CAMP_ALL_COURSES_START', //获取当前年级的所有课程
    FETCH_WINTER_CAMP_ALL_COURSES_SUCCESS:'FETCH_WINTER_CAMP_ALL_COURSES_SUCCESS',
    FETCH_WINTER_CAMP_ALL_COURSES_FAIL:'FETCH_WINTER_CAMP_ALL_COURSES_FAIL',

    SELECT_WINTER_CAMP_COURSE:'SELECT_WINTER_CAMP_COURSE',//当前选择的课程


    FETCH_WINTER_CAMP_CURRENT_COURSE_INFO_START:'FETCH_WINTER_CAMP_CURRENT_COURSE_INFO_START',//获取当前可是的任务信息
    FETCH_WINTER_CAMP_CURRENT_COURSE_INFO_SUCCESS:'FETCH_WINTER_CAMP_CURRENT_COURSE_INFO_SUCCESS',//获取当前可是的任务信息
    FETCH_WINTER_CAMP_CURRENT_COURSE_INFO_FAIL:'FETCH_WINTER_CAMP_CURRENT_COURSE_INFO_FAIL',//获取当前可是的任务信息
    CHANGE_AD_SHOW_FLAG:'CHANGE_AD_SHOW_FLAG',

    CHANGE_WINTER_CAMP_SHARE_RECORD:'CHANGE_WINTER_CAMP_SHARE_RECORD',//修改分享记录

    CHANGE_STUDY_COURSE_COUNT:'CHANGE_STUDY_COURSE_COUNT',//修改学习的时间
    CHANGE_STUDY_COURSE_COUNT_STATUS:'CHANGE_STUDY_COURSE_COUNT_STATUS',//修改学习课时的状态
};

export const WINTER_CAMP_GAME = {
    FETCH_WINTER_CAMP_GAME_LIST_START: 'FETCH_WINTER_CAMP_GAME_LIST_START',
    FETCH_WINTER_CAMP_GAME_LIST_SUCCESS: 'FETCH_WINTER_CAMP_GAME_LIST_SUCCESS',
    FETCH_WINTER_CAMP_GAME_LIST_FAIL: 'FETCH_WINTER_CAMP_GAME_LIST_FAIL',

    SELECT_WINTER_CAMP_GAME: 'SELECT_WINTER_CAMP_GAME',
};
export const WINTER_CAMP_VIP = {
    FETCH_VIP_GOODS_LIST_START:'FETCH_VIP_GOODS_LIST_START',
    FETCH_VIP_GOODS_LIST_SUCCESS:'FETCH_VIP_GOODS_LIST_SUCCESS',
    FETCH_VIP_GOODS_LIST_FAIL:'FETCH_VIP_GOODS_LIST_FAIL',
    CHANGE_WINTER_CAMP_VIP_SELECT_GOODS:'CHANGE_WINTER_CAMP_VIP_SELECT_GOODS',
    WINTER_CAMP_GOODS_CREATE_ORDER_START:'WINTER_CAMP_GOODS_CREATE_ORDER_START',
    WINTER_CAMP_GOODS_CREATE_ORDER_SUCCESS:'WINTER_CAMP_GOODS_CREATE_ORDER_SUCCESS',
    WINTER_CAMP_GOODS_CREATE_ORDER_FAIL:'WINTER_CAMP_GOODS_CREATE_ORDER_FAIL',
    WINTER_CAMP_GOODS_QUERY_ORDER_INFO_START:'WINTER_CAMP_GOODS_QUERY_ORDER_INFO_START',
    WINTER_CAMP_GOODS_QUERY_ORDER_INFO_SUCCESS:'WINTER_CAMP_GOODS_QUERY_ORDER_INFO_SUCCESS',
    WINTER_CAMP_GOODS_QUERY_ORDER_INFO_FAIL:'WINTER_CAMP_GOODS_QUERY_ORDER_INFO_FAIL',
    CHANGE_WINTER_CAMP_GOODS_CREATE_ORDER_STATUS:'CHANGE_WINTER_CAMP_GOODS_CREATE_ORDER_STATUS',
};