/**
 * Created by WL on 2017/9/5.
 */

export const FETCH_ORAL_CALCULATION_PAPER_START = "FETCH_ORAL_CALCULATION_PAPER_START";
export const FETCH_ORAL_CALCULATION_PAPER_SUCCESS = "FETCH_ORAL_CALCULATION_PAPER_SUCCESS";
export const FETCH_ORAL_CALCULATION_PAPER_FAIL = "FETCH_ORAL_CALCULATION_PAPER_FAIL";

export const ORAL_CALCULATION_WORK_LIST_SELECT_WORK = 'ORAL_CALCULATION_WORK_LIST_SELECT_WORK';