/**
 * Created by qiyuexi on 2018/1/5.
 */
/*游戏列表*/
export const GAME_LIST = {
    FETCH_GAME_LIST_START: 'FETCH_GAME_LIST_START',
    FETCH_GAME_LIST_SUCCESS: 'FETCH_GAME_LIST_SUCCESS',
    FETCH_GAME_LIST_FAILED: 'FETCH_GAME_LIST_FAILED',

    FETCH_LEVEL_LIST_START: "FETCH_LEVEL_LIST_START",
    FETCH_LEVEL_LIST_SUCCESS: "FETCH_LEVEL_LIST_SUCCESS",
    FETCH_LEVEL_LIST_FAIL: "FETCH_LEVEL_LIST_FAIL",

    CHECK_IS_GAME_CAN_PLAY_START: "CHECK_IS_GAME_CAN_PLAY_START",
    CHECK_IS_GAME_CAN_PLAY_SUCCESS: "CHECK_IS_GAME_CAN_PLAY_SUCCESS",
    CHECK_IS_GAME_CAN_PLAY_FAIL: "CHECK_IS_GAME_CAN_PLAY_FAIL",

    GAME_LIST_SELECT_GAME: 'GAME_LIST_SELECT_GAME',
    GAME_LIST_CHANGE_SEQ: 'GAME_LIST_CHANGE_SEQ',
    GAME_LIST_CHANGE_CLAZZ: 'GAME_LIST_CHANGE_CLAZZ',

    CHANGE_GAME_LIST_PAGINATION_INFO: "CHANGE_GAME_LIST_PAGINATION_INFO"
};
/*个人信息*/
export const PROFILE = {
    SET_LOCAL_STATE_FOR_USER: "SET_LOCAL_STATE_FOR_USER",
    SET_DEFAULT_STATE_FOR_USER: "SET_DEFAULT_STATE_FOR_USER",
};