/**
 * Created by WW on 2018/1/5.
 */
export const QUESTION_EVERY_DAY = {
    //获取每日一题作业列表
    FETCH_QUESTION_EVERY_DAY_LIST_START:'FETCH_QUESTION_EVERY_DAY_LIST_START',
    FETCH_QUESTION_EVERY_DAY_LIST_SUCCESS:'FETCH_QUESTION_EVERY_DAY_LIST_SUCCESS',
    FETCH_QUESTION_EVERY_DAY_LIST_FAIL:'FETCH_QUESTION_EVERY_DAY_LIST_FAIL',
    CHANGE_QUESTION_EVERY_DAY_SELECTED_WORK:'CHANGE_QUESTION_EVERY_DAY_SELECTED_WORK',
};
