/**
 * Created by ZL on 2018/3/12.
 */

//口算跨单元组卷
export const PUB_ORAL_WORK_DIFF_UNIT={
    FETCH_TEMP_ORAL_PAPER_QUES_START:'FETCH_TEMP_ORAL_PAPER_QUES_START',
    FETCH_TEMP_ORAL_PAPER_QUES_FAIL:'FETCH_TEMP_ORAL_PAPER_QUES_FAIL',
    FETCH_TEMP_ORAL_PAPER_QUES_SUCCESS:'FETCH_TEMP_ORAL_PAPER_QUES_SUCCESS',
    CHANGE_ORAL_PAPER_SET_PARAMS:'CHANGE_ORAL_PAPER_SET_PARAMS',//修改试卷设置信息（每单元选择题数，难以成都修改）
    CHANGE_ORAL_PAPER_NAME:'CHANGE_ORAL_PAPER_NAME',//修改试卷名
    PUBLISH_TEMP_ORAL_PAPER_SUCCESS:'PUBLISH_TEMP_ORAL_PAPER_SUCCESS',//作业发布成功
    CLEAR_ORAL_PAPER_DATA:'CLEAR_ORAL_PAPER_DATA',//清空试卷试题信息

    COMPOSE_ORAL_MULTI_UNIT_PAPER_START:'COMPOSE_ORAL_MULTI_UNIT_PAPER_START', //组卷开始
    COMPOSE_ORAL_MULTI_UNIT_PAPER_FAIL:'COMPOSE_ORAL_MULTI_UNIT_PAPER_FAIL', //组卷失败
    COMPOSE_ORAL_MULTI_UNIT_PAPER_SUCCESS:'COMPOSE_ORAL_MULTI_UNIT_PAPER_SUCCESS',//组卷成功
};