/**
 * Created by ZL on 2018/3/22.
 */
export const BOOK_TYPE = {
    FETCH_SELECT_BOOK_INFO_START: 'FETCH_SELECT_BOOK_INFO_START',//获取教材
    FETCH_SELECT_BOOK_INFO_SUCCESS: 'FETCH_SELECT_BOOK_INFO_SUCCESS',
    FETCH_SELECT_BOOK_INFO_FAIL: 'FETCH_SELECT_BOOK_INFO_FAIL',
};

export const EDITING_QUES = {
    SELECT_BOOK_TYPE: 'SELECT_BOOK_TYPE',//选择教材
    SELECT_CHAPTER_UNIT: 'SELECT_CHAPTER_UNIT',//选择课时和单元
    SELECT_KNOWLEDGE_POINT: 'SELECT_KNOWLEDGE_POINT',//选知识点
    SELECT_DIFFICULTY_LEVEL: 'SELECT_DIFFICULTY_LEVEL',//选择难度
    CLEAR_EDITING_QUES: 'CLEAR_EDITING_QUES',//清空选择的题目知识点信息
};

export const QUES_CONTENT = {
    SELECT_QUES_TYPE: 'SELECT_QUES_TYPE',//选择题目类型（目前只有选择题一种题型）
    SAVE_QUES_TITLE: 'SAVE_QUES_TITLE',//保存题干
    SAVE_QUES_IMG_LIST: 'SAVE_QUES_IMG_LIST',//保存图片列表
    SAVE_QUES_ANS_OPTIONS: 'SAVE_QUES_ANS_OPTIONS',//保存答案选项
    CLEAR_QUES_CONTENT: 'CLEAR_QUES_CONTENT',//清空题干、图片、选项信息
};

export const MAKE_PAPER = {
    MAKE_PAPER_FROM_TEACHER_QB_START:'MAKE_PAPER_FROM_TEACHER_QB_START',
    MAKE_PAPER_FROM_TEACHER_QB_SUCCESS:'MAKE_PAPER_FROM_TEACHER_QB_SUCCESS',
    MAKE_PAPER_FROM_TEACHER_QB_FAIL:'MAKE_PAPER_FROM_TEACHER_QB_FAIL',
    CHANGE_NAME_MAKE_PAPER_FROM_TEACHER:'CHANGE_NAME_MAKE_PAPER_FROM_TEACHER',
    CLEAR_TEMP_MAKE_PAPER:'CLEAR_TEMP_MAKE_PAPER'
};
