/**
 * Created by qiyuexi on 2018/4/25.
 */
import './constants/index'
import './directives/index'
import './services/live_service'
import './module'
import './pages/live_home/index'
import './pages/live_course_enter/index'
import './pages/live_select_question/index'
import './pages/live_work_detail/index'
import './pages/live_course_verify/index'
import './pages/live_course_detail/index'
import './pages/live_course_pay/index'
import './pages/live_do_question/index'
import './pages/live_course_pay_protocol/index'
import './pages/live_course_pay_result/index'
import './pages/live_course_iframe/index'
import './pages/live_course_fee_paper/index'
import './pages/live_course_video/index'
import './pages/live_course_video_iframe/index'