/**
 * Created by ZL on 2018/1/15.
 */
/**
 * 奥数
 * @type {{}}
 */
export const OLYMPIC_MATH = {
    OLYMPIC_MATH_CHANGE_GRADE: 'OLYMPIC_MATH_CHANGE_GRADE',//奥数改变年级
    OLYMPIC_MATH_CHANGE_CLAZZ: 'OLYMPIC_MATH_CHANGE_CLAZZ',//奥数改变班级
    CHANGE_WORK_LIST_URL_FROM: 'CHANGE_WORK_LIST_URL_FROM',//奥数改变UrlFrom到store

    OLYMPIC_MATH_HOME_DATA_START: "OLYMPIC_MATH_HOME_DATA_START",    //获取奥数主页信息开始
    OLYMPIC_MATH_HOME_DATA_SUCCESS: "OLYMPIC_MATH_HOME_DATA_SUCCESS",    //获取奥数主页信息开始成功
    OLYMPIC_MATH_HOME_DATA_FAIL: "OLYMPIC_MATH_HOME_DATA_FAIL"     //获取奥数主页信息开始失败

};

/**
 * 微信支付
 */
export const WEIXIN_PAY={
       //奥数支付
    FETCH_WEI_XIN_PAY_02_GOODS_START: "FETCH_WEI_XIN_PAY_02_GOODS_START",    //获取奥数商品信息开始
    FETCH_WEI_XIN_PAY_02_GOODS_SUCCESS: "FETCH_WEI_XIN_PAY_02_GOODS_SUCCESS",    //获取奥数商品信息成功
    FETCH_WEI_XIN_PAY_02_GOODS_FAIL: "FETCH_WEI_XIN_PAY_02_GOODS_FAIL",     //获取奥数商品信息失败

    FETCH_WEI_XIN_PAY_02_CREATE_ORDER_START:"FETCH_WEI_XIN_PAY_02_CREATE_ORDER_START", // 奥数 创建订单
    FETCH_WEI_XIN_PAY_02_CREATE_ORDER_SUCCESS:"FETCH_WEI_XIN_PAY_02_CREATE_ORDER_SUCCESS", // 奥数 创建订单成功
    FETCH_WEI_XIN_PAY_02_CREATE_ORDER_FAIL:"FETCH_WEI_XIN_PAY_02_CREATE_ORDER_FAIL", // 奥数 创建订单失败
    CHANGE_WEI_XIN_PAY_02_ORDER_STATUS:"CHANGE_WEI_XIN_PAY_02_ORDER_STATUS", // 奥数 改变订单状态

    FETCH_WEI_XIN_PAY_02_QUERY_ORDER_START:"FETCH_WEI_XIN_PAY_02_QUERY_ORDER_START", // 奥数 查询订单
    FETCH_WEI_XIN_PAY_02_QUERY_ORDER_SUCCESS:"FETCH_WEI_XIN_PAY_02_QUERY_ORDER_SUCCESS", // 奥数 查询订单成功
    FETCH_WEI_XIN_PAY_02_QUERY_ORDER_FAIL:"FETCH_WEI_XIN_PAY_02_QUERY_ORDER_FAIL", // 奥数 查询订单失败

    SAVE_WEI_XIN_PAY_02_SELECT_GOODS:"SAVE_WEI_XIN_PAY_02_SELECT_GOODS",//保存选择的商品

    SAVE_WEI_XIN_PAY_02_SELECT_GRADE:"SAVE_WEI_XIN_PAY_02_SELECT_GRADE",//保存选择的年级


};