/**
 * Created by ZL on 2018/1/15.
 */
/**
 * 微信支付
 */
export const WEIXIN_PAY={
    FETCH_WEI_XIN_PAY_CREATE_ORDER_START:"fetch_wei_xin_pay_create_order_start", //创建订单
    FETCH_WEI_XIN_PAY_CREATE_ORDER_SUCCESS:"fetch_wei_xin_pay_create_order_success", //创建订单成功
    FETCH_WEI_XIN_PAY_CREATE_ORDER_FAIL:"fetch_wei_xin_pay_create_order_fail", //创建订单失败
    CHANGE_WEI_XIN_PAY_ORDER_STATUS:"change_wei_xin_pay_order_status", //改变订单状态
    FETCH_WEI_XIN_PAY_QUERY_ORDER_START:"fetch_wei_xin_pay_query_order_start", //查询订单
    FETCH_WEI_XIN_PAY_QUERY_ORDER_SUCCESS:"fetch_wei_xin_pay_query_order_success", //查询订单成功
    FETCH_WEI_XIN_PAY_QUERY_ORDER_FAIL:"fetch_wei_xin_pay_query_order_fail", //查询订单失败

    FETCH_PAY_DETAIL_START: "FETCH_GOODS_MENUS_START",    //获取支付明细开始
    FETCH_PAY_DETAIL_SUCCESS: "FETCH_GOODS_MENUS_SUCCESS",    //获取支付明细成功
    FETCH_PAY_DETAIL_FAIL: "FETCH_GOODS_MENUS_FAIL",     //获取支付明细失败
    SAVE_PAY_DETAIL:"SAVE_PAY_DETAIL", //保存支付明细

    FETCH_GROUP_BUYING_GOODS_MENUS_START: "FETCH_GROUP_BUYING_GOODS_MENUS_START",    //获取团购商品信息开始
    FETCH_GROUP_BUYING_GOODS_MENUS_SUCCESS: "FETCH_GROUP_BUYING_GOODS_MENUS_SUCCESS",    //获取团购商品信息成功
    FETCH_GROUP_BUYING_GOODS_MENUS_FAIL: "FETCH_GROUP_BUYING_GOODS_MENUS_FAIL",     //获取团购商品信息失败
    SAVE_GROUP_BUYING_GOODS_LIST:"GROUP_BUYING_GOODS_LIST",//保存团购商品列表

    SAVE_GROUP_BUYING_GOODS:"SELECTED_GROUP_BUYING_GOOD",//团购信息
    FETCH_GROUP_BUYING_CREATE_ORDER_START:"FETCH_GROUP_BUYING_CREATE_ORDER_START", //团购创建订单
    FETCH_GROUP_BUYING_CREATE_ORDER_SUCCESS:"FETCH_GROUP_BUYING_CREATE_ORDER_SUCCESS", //团购创建订单成功
    FETCH_GROUP_BUYING_CREATE_ORDER_FAIL:"FETCH_GROUP_BUYING_CREATE_ORDER_FAIL", //团购创建订单失败
    CHANGE_GROUP_BUYING_ORDER_STATUS:"CHANGE_GROUP_BUYING_ORDER_STATUS", //团购改变订单状态

    FETCH_GROUP_BUYING_ORDER_START:"FETCH_GROUP_BUYING_ORDER_START", //查询团购订单开始
    FETCH_GROUP_BUYING_ORDER_SUCCESS:"FETCH_GROUP_BUYING_ORDER_SUCCESS", //查询团购订单成功
    FETCH_GROUP_BUYING_ORDER_FAIL:"FETCH_GROUP_BUYING_ORDER_FAIL", //查询团购订单失败
};