import "./src/ocLazyLoad.core"
import "./src/ocLazyLoad.directive"
import "./src/ocLazyLoad.loaders.common"
import "./src/ocLazyLoad.loaders.core"
import "./src/ocLazyLoad.loaders.cssLoader"
import "./src/ocLazyLoad.loaders.jsLoader"
import "./src/ocLazyLoad.loaders.templatesLoader"
import "./src/ocLazyLoad.polyfill.ie8"