/**
 * Created by ZL on 2017/11/6.
 */
export const TEACHER_TASK = {
    FETCH_TASK_LIST_START: "FETCH_TASK_LIST_START",//获取教师任务开始
    FETCH_TASK_LIST_SUCCESS: "FETCH_TASK_LIST_SUCCESS",//获取教师任务成功
    FETCH_TASK_LIST_FAIL: "FETCH_TASK_LIST_FAIL",//获取教师任务失败

    SELECT_TEACHER_TASK:'SELECT_TEACHER_TASK',//选择任务
};

export const GET_DEFAULT_RECEIVER_START = 'GET_DEFAULT_RECEIVER_START';//获取默认收件人
export const GET_DEFAULT_RECEIVER_SUCCESS = 'GET_DEFAULT_RECEIVER_SUCCESS';//获取默认收件人
export const GET_DEFAULT_RECEIVER_FAIL = 'GET_DEFAULT_RECEIVER_FAIL';//获取默认收件人
// export const CHANGE_DEFAULT_RECEIVER_START = 'CHANGE_DEFAULT_RECEIVER_START';//修改默认收件人
// export const CHANGE_DEFAULT_RECEIVER_SUCCESS = 'CHANGE_DEFAULT_RECEIVER_SUCCESS';//修改默认收件人
// export const CHANGE_DEFAULT_RECEIVER_FAIL = 'CHANGE_DEFAULT_RECEIVER_FAIL';//修改默认收件人
export const CREDITS_DETAIL = {
    FETCH_CREDITS_DETAIL_START: "FETCH_CREDITS_DETAIL_START",//获取积分开始
    FETCH_CREDITS_DETAIL_SUCCESS: "FETCH_CREDITS_DETAIL_SUCCESS",//获取积分成功
    FETCH_CREDITS_DETAIL_FAIL: "FETCH_CREDITS_DETAIL_FAIL",//获取积分失败
};

export const CREDITS_GOODS={
    FETCH_CREDITS_GOODS_LIST_START:'FETCH_CREDITS_GOODS_LIST_START',//获取商品列表
    FETCH_CREDITS_GOODS_LIST_SUCCESS:'FETCH_CREDITS_GOODS_LIST_SUCCESS',//获取商品列表
    FETCH_CREDITS_GOODS_LIST_FAIL:'FETCH_CREDITS_GOODS_LIST_FAIL',//获取商品列表
    FETCH_CREDITS_GOODS_LIST_MORE:'FETCH_CREDITS_GOODS_LIST_MORE',//获取商品列表

    SELECT_CREDITS_GOODS:'SELECT_CREDITS_GOODS',//选择商品
};
export const RATORY_INFO = {
    FETCH_RATORY_INFO_START: "FETCH_RATORY_INFO_START",//获取奖品信息开始
    FETCH_RATORY_INFO_SUCCESS: "FETCH_RATORY_INFO_SUCCESS",//获取奖品信息成功
    FETCH_RATORY_INFO_FAIL: "FETCH_RATORY_INFO_FAIL",//获取奖品信息失败
};
