/**
 * Created by qiyuexi on 2017/12/8.
 */
export const FINAL_SPRINT_GOODS={ //支付商品
    FETCH_SPRINT_GOODS_LIST_START:'FETCH_SPRINT_GOODS_LIST_START',//获取商品列表
    FETCH_SPRINT_GOODS_LIST_SUCCESS:'FETCH_SPRINT_GOODS_LIST_SUCCESS',
    FETCH_SPRINT_GOODS_LIST_FAIL:'FETCH_SPRINT_GOODS_LIST_FAIL',
    SELECT_SPRINT_GOODS:'SELECT_SPRINT_GOODS',//选择的商品

    SPRINT_GOODS_CREATE_ORDER_START:'SPRINT_GOODS_CREATE_ORDER_START', //创建订单
    SPRINT_GOODS_CREATE_ORDER_SUCCESS:'SPRINT_GOODS_CREATE_ORDER_SUCCESS',
    SPRINT_GOODS_CREATE_ORDER_FAIL:'SPRINT_GOODS_CREATE_ORDER_FAIL',
    CHANGE_SPRINT_GOODS_CREATE_ORDER_STATUS:'CHANGE_SPRINT_GOODS_CREATE_ORDER_STATUS',//修改订单

    SPRINT_GOODS_QUERY_ORDER_INFO_START:'SPRINT_GOODS_QUERY_ORDER_INFO_START', //查询订单信息
    SPRINT_GOODS_QUERY_ORDER_INFO_SUCCESS:'SPRINT_GOODS_QUERY_ORDER_INFO_SUCCESS',
    SPRINT_GOODS_QUERY_ORDER_INFO_FAIL:'SPRINT_GOODS_QUERY_ORDER_INFO_FAIL',
};