/*班级*/
export const CLAZZ = {
    FETCH_CLAZZ_LIST_START: "FETCH_CLAZZ_LIST_START",
    FETCH_CLAZZ_LIST_SUCCESS: "FETCH_CLAZZ_LIST_SUCCESS",
    FETCH_CLAZZ_LIST_FAIL: "FETCH_CLAZZ_LIST_FAIL",
    CHANGE_CLAZZ: 'CHANGE_CLAZZ',
    SAVE_TEACHER_MSG:'SAVE_TEACHER_MSG'
};
/*作业列表*/
export const WORK_LIST = {
    FETCH_WORK_LIST_START: 'FETCH_WORK_LIST_START',
    FETCH_WORK_LIST_SUCCESS: 'FETCH_WORK_LIST_SUCCESS',
    FETCH_WORK_LIST_FAILED: 'FETCH_WORK_LIST_FAILED',
    WORK_LIST_CHANGE_CLAZZ: 'WORK_LIST_CHANGE_CLAZZ',
    DELETE_SELF_TRAIN_WORK: 'DELETE_SELF_TRAIN_WORK',
    CHANGE_WORK_LIST_PAGINATION_INFO: "CHANGE_WORK_LIST_PAGINATION_INFO",

    CHANGE_CLASS_PAGINATION_INFO: "CHANGE_CLASS_PAGINATION_INFO",

    FETCH_WORK_STATUS_START: 'FETCH_WORK_STATUS_START',
    FETCH_WORK_STATUS_SUCCESS: 'FETCH_WORK_STATUS_SUCCESS',
    FETCH_WORK_STATUS_FAILED: 'FETCH_WORK_STATUS_FAILED',

    WORK_LIST_SELECT_WORK: "WORK_LIST_SELECT_WORK",

    WORK_LIST_FETCH_PAPER_START: 'WORK_LIST_FETCH_PAPER_START',
    WORK_LIST_FETCH_PAPER_SUCCESS: 'WORK_LIST_FETCH_PAPER_SUCCESS',
    WORK_LIST_FETCH_PAPER_FAILED: 'WORK_LIST_FETCH_PAPER_FAILED',

    WORK_LIST_FETCH_DO_PAPER_START: 'WORK_LIST_FETCH_DO_PAPER_START',
    WORK_LIST_FETCH_DO_PAPER_SUCCESS: 'WORK_LIST_FETCH_DO_PAPER_SUCCESS',
    WORK_LIST_FETCH_DO_PAPER_FAILED: 'WORK_LIST_FETCH_DO_PAPER_FAILED',

    FETCH_WORK_STU_PRAISE_START: "FETCH_WORK_STU_PRAISE_START",
    FETCH_WORK_STU_PRAISE_SUCCESS: "FETCH_WORK_STU_PRAISE_SUCCESS",
    FETCH_WORK_STU_PRAISE_FAILED: "FETCH_WORK_STU_PRAISE_FAILED",

    CONFIRM_STU_PRAISE_START: "CONFIRM_STU_PRAISE_START",
    CONFIRM_STU_PRAISE_SUCCESS: "CONFIRM_STU_PRAISE_SUCCESS",
    CONFIRM_STU_PRAISE_FAILED: "CONFIRM_STU_PRAISE_FAILED",

    SUBMIT_PAPER_MODIFY_PAPER_STATUS: "SUBMIT_PAPER_MODIFY_PAPER_STATUS", //提交试卷后更新试卷状态为已提交
    QUESTION_STATUS_MODIFY_FLAG_FALSE: "QUESTION_STATUS_MODIFY_FLAG_FALSE", //设置试卷题目状态是否更新的flag为false

    SELECT_QUESTION_PARSE_PAPER_DATA: 'SELECT_QUESTION_PARSE_PAPER_DATA',//进入select_question页面从后端取题成功后,解析保存需要的题目格式
    SELECT_QUESTION_CHECK_ASSIGNED_QUESTION: 'SELECT_QUESTION_CHECK_ASSIGNED_QUESTION',//从select_question页面进入do_question页面,获取保存点击的小题信息:bigQIndex,smallQIndex,questionIndex,form


    DO_QUESTION_FILL_SLIDE_BOX_DATA: "DO_QUESTION_FILL_SLIDE_BOX_DATA", //初始化试卷slideBox三个页面中的题目试卷
    DO_QUESTION_REFRESH_CURRENT_SMALL_Q: "DO_QUESTION_REFRESH_CURRENT_SMALL_Q", //slide页面变化时,更新试卷(doPaper)中的当前题目信息:bigQIndex,smallQIndex,questionIndex
    DO_QUESTION_REFRESH_SLIDE_BOX_LIST: "DO_QUESTION_REFRESH_SLIDE_BOX_LIST", //更新试卷中slideBox三个页面中的题目数据
    DO_QUESTION_BACK_TO_SELECT: 'DO_QUESTION_BACK_TO_SELECT', //从do_question页面返回到select_question页面,改变paperData.from的值为'do_question'
    DO_QUESTION_CHECK_QUESTION_OK: 'DO_QUESTION_CHECK_QUESTION_OK', //do_question也检查答案OK,后更新该小题状态
    DO_QUESTION_MODIFY_QUESTION_STATUS: 'DO_QUESTION_MODIFY_QUESTION_STATUS', //保存答案,更新小题的状态(保存答案时)
    DO_QUESTION_MODIFY_QUESTION_INPUTLIST: 'DO_QUESTION_MODIFY_QUESTION_INPUTLIST', //保存答案,更新小题的inputList
    DO_QUESTION_SAVE_QUESTION_ANS: 'DO_QUESTION_SAVE_QUESTION_ANS', //保存答案,存入临时数组paperData.questionAnsArr
    DO_QUESTION_REMOVE_QUESTION_ANS: 'DO_QUESTION_REMOVE_QUESTION_ANS', //答案提交到服务器,清空临时数组paperData.questionAnsArr
    SELECT_QUESTION_FILL_PAPER_WITH_LOCAL_ANS: 'SELECT_QUESTION_FILL_PAPER_WITH_LOCAL_ANS', //使用未上传的小题答案, 填充到paperData中

    DELETE_CACHED_WORK_LIST: "DELETE_CACHED_WORK_LIST",

};
/*个人信息*/
export const PROFILE = {
    SELECTED_GOOD: "SELECTED_GOOD",
    LOGIN_START: "LOGIN_START",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGOUT_START: "LOGOUT_START",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAIL: "LOGOUT_FAIL",
    PROFILE_CHANGE_CLAZZ: 'PROFILE_CHANGE_CLAZZ',
    CHECK_IS_VALID_SESSION_START: 'CHECK_IS_VALID_SESSION_START',
    CHECK_IS_VALID_SESSION_SUCCESS: 'CHECK_IS_VALID_SESSION_SUCCESS',
    CHECK_IS_VALID_SESSION_FAIL: 'CHECK_IS_VALID_SESSION_FAIL',
    SET_LOCAL_STATE_FOR_USER: "SET_LOCAL_STATE_FOR_USER",
    SET_DEFAULT_STATE_FOR_USER: "SET_DEFAULT_STATE_FOR_USER",
    USER_LOGOUT_BY_SELF: "USER_LOGOUT_BY_SELF",
    USER_IS_VIP_DIAGNOSE:"USER_IS_VIP_DIAGNOSE",
    USER_IS_VIP_MATH_OLY:"USER_IS_VIP_MATH_OLY",
    USER_IS_VIP_XLY:"USER_IS_VIP_XLY",
    USER_IS_VIP_FINAL_SPRINT:"USER_IS_VIP_FINAL_SPRINT",
    CLICK_NATIONAL_DAY_GIFT_PACKAGE:'CLICK_NATIONAL_DAY_GIFT_PACKAGE', //点击国庆大礼包
    CLICK_NATIONAL_DAY_GIFT_PACKAGE_11_11:'CLICK_NATIONAL_DAY_GIFT_PACKAGE_11_11', //点击双11大礼包
    MODIFY_DURING_NATIONAL_DAY_FLAG:"MODIFY_DURING_NATIONAL_DAY_FLAG",
    MODIFY_VIPS_INFO:'MODIFY_VIPS_INFO',
    CHANGE_CHECKED_OLYMPIC_CHANGE_AD_FLAG:"CHANGE_CHECKED_OLYMPIC_CHANGE_AD_FLAG",
    UPDATE_GAME_VIP:"UPDATE_GAME_VIP",

};
/*todo game_list已经独立出来 游戏列表 sharding_clazz和Profile_service.js在用 */
export const GAME_LIST = {
    FETCH_GAME_LIST_START: 'FETCH_GAME_LIST_START',
    FETCH_GAME_LIST_SUCCESS: 'FETCH_GAME_LIST_SUCCESS',
    FETCH_GAME_LIST_FAILED: 'FETCH_GAME_LIST_FAILED',

    FETCH_LEVEL_LIST_START: "FETCH_LEVEL_LIST_START",
    FETCH_LEVEL_LIST_SUCCESS: "FETCH_LEVEL_LIST_SUCCESS",
    FETCH_LEVEL_LIST_FAIL: "FETCH_LEVEL_LIST_FAIL",

    CHECK_IS_GAME_CAN_PLAY_START: "CHECK_IS_GAME_CAN_PLAY_START",
    CHECK_IS_GAME_CAN_PLAY_SUCCESS: "CHECK_IS_GAME_CAN_PLAY_SUCCESS",
    CHECK_IS_GAME_CAN_PLAY_FAIL: "CHECK_IS_GAME_CAN_PLAY_FAIL",

    GAME_LIST_SELECT_GAME: 'GAME_LIST_SELECT_GAME',
    GAME_LIST_CHANGE_SEQ: 'GAME_LIST_CHANGE_SEQ',
    GAME_LIST_CHANGE_CLAZZ: 'GAME_LIST_CHANGE_CLAZZ',

    CHANGE_GAME_LIST_PAGINATION_INFO: "CHANGE_GAME_LIST_PAGINATION_INFO"
};
/*我的成就*/
export const ACHIEVEMENT = {
    FETCH_ACHIEVEMENT_START: 'FETCH_ACHIEVEMENT_START',
    FETCH_ACHIEVEMENT_SUCCESS: 'FETCH_ACHIEVEMENT_SUCCESS',
    FETCH_ACHIEVEMENT_FAIL: 'FETCH_ACHIEVEMENT_FAIL'
};

/*奖杯排行*/
export const TROPHY_RANK = {
    TROPHY_CHANGE_CLAZZ: 'TROPHY_CHANGE_CLAZZ',//奖杯排行页面改变班级
    FETCH_TROPHY_RANK_START: 'FETCH_TROPHY_RANK_START',
    FETCH_TROPHY_RANK_SUCCESS: 'FETCH_TROPHY_RANK_SUCCESS',
    FETCH_TROPHY_RANK_FAIL: 'FETCH_TROPHY_RANK_FAIL',
    TROPHY_CHANGE_TIME: 'TROPHY_CHANGE_TIME'//奖杯排行页面改变选择时间
};

/*应用信息*/
export const APP_INFO = {
    FETCH_APP_INFO_SUCCESS: 'FETCH_APP_INFO_SUCCESS',
    FETCH_APP_INFO_FAIL: 'FETCH_APP_INFO_FAIL',
    FETCH_APP_CHANGE_LOG_SUCCESS: 'FETCH_APP_CHANGE_LOG_SUCCESS',
    FETCH_APP_CHANGE_LOG_FAIL: 'FETCH_APP_CHANGE_LOG_FAIL',
    CHANGE_NETWORK_STATUS: "CHANGE_NETWORK_STATUS"
};
/*问题反馈*/
export const FEEDBACK = {
    SUGGESTION_WORD: 'SUGGESTION_WORD',
    SAVE_SUGGESTION_GO_BACK: 'SAVE_SUGGESTION_GO_BACK',
    SUBMIT_SUGGESTION_START: 'SUBMIT_SUGGESTION_START',
    SUBMIT_SUGGESTION_SUCCESS: 'SUBMIT_SUGGESTION_SUCCESS',
    SUBMIT_SUGGESTION_FAIL: 'SUBMIT_SUGGESTION_FAIL'
};
/*大题列表*/
export const SELECT_QUESTION = {
    FETCH_PAPER_START: 'FETCH_PAPER_START',
    FETCH_PAPER_SUCCESS: 'FETCH_PAPER_SUCCESS',
    FETCH_PAPER_FAIL: 'FETCH_PAPER_FAIL',
    SUBMIT_PAPER_START: 'SUBMIT_PAPER_START',
    SUBMIT_PAPER_SUCCESS: 'SUBMIT_PAPER_SUCCESS',
    SUBMIT_PAPER_FAILED: 'SUBMIT_PAPER_FAILED',
    POST_ANSWER_START: 'POST_ANSWER_START',
    POST_ANSWER_SUCCESS: 'POST_ANSWER_SUCCESS',
    POST_ANSWER_FAILED: 'POST_ANSWER_FAILED',


    INITIALIZE_PAPER_TIME_COLLECTOR: "INITIALIZE_PAPER_TIME_COLLECTOR", //进入select_question页面,初始化一个时间计时器列表
    START_PAPER_TIME_COLLECTOR: "START_PAPER_TIME_COLLECTOR", //进入select_question页面,开始本试卷答题计时

    MODIFY_PAPER_ANSWER: 'MODIFY_PAPER_ANSWER', //更新指定试卷的答案
    CLEAR_PAPER_ANSWER: 'CLEAR_PAPER_ANSWER', //清空指定试卷的答案
};

/**
 * 单元
 * @type {{}}
 */
export const UNIT = {
    FETCH_UNIT_START: "FETCH_UNIT_START",//获取单元开始
    FETCH_UNIT_SUCCESS: "FETCH_UNIT_SUCCESS",//获取单元成功
    FETCH_UNIT_FAIL: "FETCH_UNIT_FAIL",//获取单元失败
    CHANGE_UNIT: "CHANGE_UNIT",        //改变单元选择
    CHANGE_TEXTBOOK_BY_CLAZZ: "CHANGE_TEXTBOOK_BY_CLAZZ",        //改变班级后改变的教材
    RESET_UNIT_STATUS: 'RESET_UNIT_STATUS',              //重置单元选中状态

    FETCH_TEXTBOOK_LIST_START: "FETCH_TEXTBOOK_LIST_START",//获取教材开始
    FETCH_TEXTBOOK_LIST_SUCCESS: "FETCH_TEXTBOOK_LIST_SUCCESS",//获取教材成功
    FETCH_TEXTBOOK_LIST_FAIL: "FETCH_TEXTBOOK_LIST_FAIL",//获取教材失败

    SELECT_TEXTBOOK_WORK: 'SELECT_TEXTBOOK_WORK'   //选中其中一本教材

};

/**
 * 诊断
 * @type {{}}
 */
export const DIAGNOSE = {

    DIAGNOSE_CHANGE_TEXTBOOK: 'DIAGNOSE_CHANGE_TEXTBOOK',//诊断当前选中的教材
    DIAGNOSE_CHANGE_GRADE: 'DIAGNOSE_CHANGE_GRADE',//诊断当前选中的年级

    FETCH_HOME_STATISTIC_START: "FETCH_HOME_STATISTIC_START",    //获取主页诊断统计信息开始
    FETCH_HOME_STATISTIC_SUCCESS: "FETCH_HOME_STATISTIC_SUCCESS",    //获取主页诊断统计信息成功
    FETCH_HOME_STATISTIC_FAIL: "FETCH_HOME_STATISTIC_FAIL",     //获取主页诊断统计信息失败

    HOME_SELECT_CHAPTER:'HOME_SELECT_CHAPTER',//诊断主页选中章节

    CHAPTER_SELECT_POINT:'CHAPTER_SELECT_POINT',//章节选中知识点

    FETCH_CHAPTER_DIAGNOSE_START: "FETCH_CHAPTER_DIAGNOSE_START",    //获取章节诊断统计信息开始
    FETCH_CHAPTER_DIAGNOSE_SUCCESS: "FETCH_CHAPTER_DIAGNOSE_SUCCESS",    //获取章节诊断统计信息成功
    FETCH_CHAPTER_DIAGNOSE_FAIL: "FETCH_CHAPTER_DIAGNOSE_FAIL",     //获取章节诊断统计信息失败

    FETCH_DIAGNOSE_REPORT_START: "FETCH_DIAGNOSE_REPORT_START",    //获取诊断报告开始
    FETCH_DIAGNOSE_REPORT_SUCCESS: "FETCH_DIAGNOSE_REPORT_SUCCESS",    //获取诊断报告成功
    FETCH_DIAGNOSE_REPORT_FAIL: "FETCH_DIAGNOSE_REPORT_FAIL",     //获取诊断报告失败


    FETCH_UNIT_STATISTIC_START: "FETCH_UNIT_STATISTIC_START",    //获取个人诊断统计信息开始
    FETCH_UNIT_STATISTIC_SUCCESS: "FETCH_UNIT_STATISTIC_SUCCESS",    //获取个人诊断统计信息成功
    FETCH_UNIT_STATISTIC_FAIL: "FETCH_UNIT_STATISTIC_FAIL",     //获取个人诊断统计信息失败

    FETCH_GOODS_MENUS_START: "FETCH_GOODS_MENUS_START",    //获取商品信息开始
    FETCH_GOODS_MENUS_SUCCESS: "FETCH_GOODS_MENUS_SUCCESS",    //获取商品信息成功
    FETCH_INCREASE_SCORE_GOODS_MENUS_SUCCESS: "FETCH_INCREASE_SCORE_GOODS_MENUS_SUCCESS",    //获取诊断提分商品信息成功
    FETCH_GOODS_MENUS_FAIL: "FETCH_GOODS_MENUS_FAIL",     //获取商品信息失败


    DIAGNOSE_CLAZZ_WITH_UNIT:"DIAGNOSE_CLAZZ_WITH_UNIT",//诊断班级关联单元

    SELECT_UNIT:'SELECT_UNIT',//诊断选中单元

    UNIT_SELECT_CHAPTER:'UNIT_SELECT_CHAPTER',//诊断选中章节

    UNIT_SELECT_KNOWLEDGE: "UNIT_SELECT_KNOWLEDGE",            //总的诊断页面选择子知识点，查看其诊断信息

    DIAGNOSE_CHANGE_CLAZZ: 'DIAGNOSE_CHANGE_CLAZZ',//诊断页面改变班级

    FETCH_CHAPTER_STATISTIC_START: "FETCH_CHAPTER_STATISTIC_START",    //获取个人章节诊断统计信息开始
    FETCH_CHAPTER_STATISTIC_SUCCESS: "FETCH_CHAPTER_STATISTIC_SUCCESS",    //获取个人章节诊断统计信息成功
    FETCH_CHAPTER_STATISTIC_FAIL: "FETCH_CHAPTER_STATISTIC_FAIL",     //获取个人章节诊断统计信息失败

    FETCH_UNIT_KNOWLEDGE_STATI_START: "FETCH_UNIT_KNOWLEDGE_STATI_START",//获取子得分点诊断统计信息开始
    FETCH_UNIT_KNOWLEDGE_STATI_SUCCESS: "FETCH_UNIT_KNOWLEDGE_STATI_SUCCESS",//获取子得分点诊断统计信息成功
    FETCH_UNIT_KNOWLEDGE_STATI_FAIL: "FETCH_UNIT_KNOWLEDGE_STATI_FAIL",    //获取子得分点诊断统计信息失败

    FETCH_Q_RECORDS_START: "FETCH_Q_RECORDS_START",//获取做题记录开始
    FETCH_Q_RECORDS_SUCCESS: "FETCH_Q_RECORDS_SUCCESS",//获取做题记录成功
    FETCH_Q_RECORDS_FAIL: "FETCH_Q_RECORDS_FAIL",   //获取做题记录失败

    FETCH_ERROR_Q_RECORDS_START: "FETCH_ERROR_Q_RECORDS_START",//获取错题记录开始
    FETCH_ERROR_Q_RECORDS_SUCCESS: "FETCH_ERROR_Q_RECORDS_SUCCESS",//获取错题记录成功
    FETCH_ERROR_Q_RECORDS_FAIL: "FETCH_ERROR_Q_RECORDS_FAIL",   //获取错题记录失败

    CHANGE_Q_RECORDS_PAGINATION_INFO: "CHANGE_Q_RECORDS_PAGINATION_INFO",//变更做题记录的分页信息

    FETCH_QUESTION_START: 'FETCH_QUESTION_START',//获取试题开始（包括改错情况）
    FETCH_QUESTION_SUCCESS: 'FETCH_QUESTION_SUCCESS',//获取试题成功（包括改错情况）
    FETCH_QUESTION_NO_QUESTION: 'FETCH_QUESTION_NO_QUESTION',//获取试题成功，但是已经没有新题了。
    FETCH_QUESTION_FAIL: 'FETCH_QUESTION_FAIL',//获取试题失败（包括改错情况）
    FETCH_QUESTION_STEP_STATUS_SUCCESS: 'FETCH_QUESTION_STEP_STATUS_SUCCESS',//获取诊断知识点的进度状态



    GO_TO_DO_QUESTION: 'GO_TO_DO_QUESTION',   //去做试题

    DIAGNOSE_SAVE_QUESTION: 'DIAGNOSE_SAVE_QUESTION',   //保存试题
    DIAGNOSE_CLEAR_QUESTION:'DIAGNOSE_CLEAR_QUESTION',   //清除知识点上的试题

    DIAGNOSE_SUBMIT_Q_START: 'DIAGNOSE_SUBMIT_Q_START', //诊断提交试题开始
    DIAGNOSE_SUBMIT_Q_SUCCESS: 'DIAGNOSE_SUBMIT_Q_SUCCESS',//诊断提交试题成功
    DIAGNOSE_SUBMIT_Q_FAIL: 'DIAGNOSE_SUBMIT_Q_FAIL', //诊断提交试题失败

    GO_TO_ERROR_RECORDS: 'GO_TO_ERROR_RECORDS', //去查看错题记录
    KNOWLEDGE_SELECTED_Q: 'KNOWLEDGE_SELECTED_Q', //去查看错题记录所选中的试题

    SUBTRACT_DIAGNOSE_REPORT_WRONG_NUM:'SUBTRACT_DIAGNOSE_REPORT_WRONG_NUM', //诊断报告中的错题待改数减掉1
    CHANGE_FIRST_SUBMIT_WORK_AFTER_UPDATE_FLAG:"CHANGE_FIRST_SUBMIT_WORK_AFTER_UPDATE_FLAG", //诊断提分考点付费更新后首次提交作业flag

    SAVE_DIAGNOSE_ENTRY_URL_FROM:'SAVE_DIAGNOSE_ENTRY_URL_FROM',//保存进入诊断的入口
};

/**
 * 奥数
 * @type {{}}
 */
export const OLYMPIC_MATH = {
    OLYMPIC_MATH_CHANGE_GRADE: 'OLYMPIC_MATH_CHANGE_GRADE',//奥数改变年级
    OLYMPIC_MATH_CHANGE_CLAZZ: 'OLYMPIC_MATH_CHANGE_CLAZZ',//奥数改变班级
    CHANGE_WORK_LIST_URL_FROM: 'CHANGE_WORK_LIST_URL_FROM',//奥数改变UrlFrom到store

    OLYMPIC_MATH_HOME_DATA_START: "OLYMPIC_MATH_HOME_DATA_START",    //获取奥数主页信息开始
    OLYMPIC_MATH_HOME_DATA_SUCCESS: "OLYMPIC_MATH_HOME_DATA_SUCCESS",    //获取奥数主页信息开始成功
    OLYMPIC_MATH_HOME_DATA_FAIL: "OLYMPIC_MATH_HOME_DATA_FAIL"     //获取奥数主页信息开始失败

};

export const APP_FLAG = {
    SAVE_LOCAL_ANS_TO_SERVER: "SAVE_LOCAL_ANS_TO_SERVER",//将本地答案保存到服务器(本地不再有答案)
    NEED_SAVE_LOCAL_ANS_TO_SERVER: "NEED_SAVE_LOCAL_ANS_TO_SERVER",//本地答案没有保存到服务器(本地有答案)

    CAN_FETCH_PAPER_TRUE: "CAN_FETCH_PAPER_TRUE",  //向服务器获取试卷详情
    CAN_FETCH_PAPER_FALSE: "CAN_FETCH_PAPER_FALSE", //使用本地的试卷详情
    CAN_FETCH_DOPAPER_TRUE: "CAN_FETCH_DOPAPER_TRUE", //向服务器获取试卷题目
    CAN_FETCH_DOPAPER_FALSE: "CAN_FETCH_DOPAPER_FALSE" //使用本地的试卷题目
};


export const STUDY_STATI = {
    FETCH_STUDY_STATI_START: "FETCH_STUDY_STATI_START",
    FETCH_STUDY_STATI_SUCCESS: "FETCH_STUDY_STATI_SUCCESS",
    FETCH_STUDY_STATI_FAIL: "FETCH_STUDY_STATI_FAIL",
    CHANGE_STUDY_STATIS_PARAMS:'CHANGE_STUDY_STATIS_PARAMS'
};


export const COMPUTE = {
    COMPUTE_CHANGE_CLAZZ: 'COMPUTE_CHANGE_CLAZZ'
};

export const FEATURE_SWITCH = {
    FETCH_FEATURE_SWITCH_START: "FETCH_FEATURE_SWITCH_START",
    FETCH_FEATURE_SWITCH_SUCCESS: "FETCH_FEATURE_SWITCH_SUCCESS",
    FETCH_FEATURE_SWITCH_FAIL: "FETCH_FEATURE_SWITCH_FAIL",
};

/**
 * 游戏星星排行
 * @type {{}}
 */
export const GAME_STAR_RANK = {
    FETCH_GAME_STAR_RANK_DATA_START:'fetch_game_star_rank_data_start', //开始获取数据
    FETCH_GAME_STAR_RANK_DATA_SUCCESS:'fetch_game_star_rank_data_success', //获取数据成功
    FETCH_GAME_STAR_RANK_DATA_FAIL:'fetch_game_star_rank_data_fail', //获取数据失败
    // SELECT_GAME_STAR_RANK_CLAZZ:'select_game_star_rank_clazz', //选择星星排行的班级
};
/**
 * 斗士排行
 * @type {{}}
 */
export const FIGHTER_RANK = {
    FETCH_FIGHTER_RANK_DATA_START:'fetch_fighter_rank_data_start', //开始获取数据
    FETCH_FIGHTER_RANK_DATA_SUCCESS:'fetch_fighter_rank_data_success', //获取数据成功
    FETCH_FIGHTER_RANK_DATA_FAIL:'fetch_fighter_rank_data_fail', //获取数据失败
    // SELECT_FIGHTER_RANK_CLAZZ:'select_fighter_rank_clazz', //选择斗士排行的班级
};

/**
 * 微信支付
 */
export const WEIXIN_PAY={
    FETCH_WEI_XIN_PAY_CREATE_ORDER_START:"fetch_wei_xin_pay_create_order_start", //创建订单
    FETCH_WEI_XIN_PAY_CREATE_ORDER_SUCCESS:"fetch_wei_xin_pay_create_order_success", //创建订单成功
    FETCH_WEI_XIN_PAY_CREATE_ORDER_FAIL:"fetch_wei_xin_pay_create_order_fail", //创建订单失败
    CHANGE_WEI_XIN_PAY_ORDER_STATUS:"change_wei_xin_pay_order_status", //改变订单状态
    FETCH_WEI_XIN_PAY_QUERY_ORDER_START:"fetch_wei_xin_pay_query_order_start", //查询订单
    FETCH_WEI_XIN_PAY_QUERY_ORDER_SUCCESS:"fetch_wei_xin_pay_query_order_success", //查询订单成功
    FETCH_WEI_XIN_PAY_QUERY_ORDER_FAIL:"fetch_wei_xin_pay_query_order_fail", //查询订单失败

    FETCH_PAY_DETAIL_START: "FETCH_GOODS_MENUS_START",    //获取支付明细开始
    FETCH_PAY_DETAIL_SUCCESS: "FETCH_GOODS_MENUS_SUCCESS",    //获取支付明细成功
    FETCH_PAY_DETAIL_FAIL: "FETCH_GOODS_MENUS_FAIL",     //获取支付明细失败
    SAVE_PAY_DETAIL:"SAVE_PAY_DETAIL", //保存支付明细

    FETCH_GROUP_BUYING_GOODS_MENUS_START: "FETCH_GROUP_BUYING_GOODS_MENUS_START",    //获取团购商品信息开始
    FETCH_GROUP_BUYING_GOODS_MENUS_SUCCESS: "FETCH_GROUP_BUYING_GOODS_MENUS_SUCCESS",    //获取团购商品信息成功
    FETCH_GROUP_BUYING_GOODS_MENUS_FAIL: "FETCH_GROUP_BUYING_GOODS_MENUS_FAIL",     //获取团购商品信息失败
    SAVE_GROUP_BUYING_GOODS_LIST:"GROUP_BUYING_GOODS_LIST",//保存团购商品列表

    SAVE_GROUP_BUYING_GOODS:"SELECTED_GROUP_BUYING_GOOD",//团购信息
    FETCH_GROUP_BUYING_CREATE_ORDER_START:"FETCH_GROUP_BUYING_CREATE_ORDER_START", //团购创建订单
    FETCH_GROUP_BUYING_CREATE_ORDER_SUCCESS:"FETCH_GROUP_BUYING_CREATE_ORDER_SUCCESS", //团购创建订单成功
    FETCH_GROUP_BUYING_CREATE_ORDER_FAIL:"FETCH_GROUP_BUYING_CREATE_ORDER_FAIL", //团购创建订单失败
    CHANGE_GROUP_BUYING_ORDER_STATUS:"CHANGE_GROUP_BUYING_ORDER_STATUS", //团购改变订单状态

    FETCH_GROUP_BUYING_ORDER_START:"FETCH_GROUP_BUYING_ORDER_START", //查询团购订单开始
    FETCH_GROUP_BUYING_ORDER_SUCCESS:"FETCH_GROUP_BUYING_ORDER_SUCCESS", //查询团购订单成功
    FETCH_GROUP_BUYING_ORDER_FAIL:"FETCH_GROUP_BUYING_ORDER_FAIL", //查询团购订单失败

    //奥数支付
    FETCH_WEI_XIN_PAY_02_GOODS_START: "FETCH_WEI_XIN_PAY_02_GOODS_START",    //获取奥数商品信息开始
    FETCH_WEI_XIN_PAY_02_GOODS_SUCCESS: "FETCH_WEI_XIN_PAY_02_GOODS_SUCCESS",    //获取奥数商品信息成功
    FETCH_WEI_XIN_PAY_02_GOODS_FAIL: "FETCH_WEI_XIN_PAY_02_GOODS_FAIL",     //获取奥数商品信息失败

    FETCH_WEI_XIN_PAY_02_CREATE_ORDER_START:"FETCH_WEI_XIN_PAY_02_CREATE_ORDER_START", // 奥数 创建订单
    FETCH_WEI_XIN_PAY_02_CREATE_ORDER_SUCCESS:"FETCH_WEI_XIN_PAY_02_CREATE_ORDER_SUCCESS", // 奥数 创建订单成功
    FETCH_WEI_XIN_PAY_02_CREATE_ORDER_FAIL:"FETCH_WEI_XIN_PAY_02_CREATE_ORDER_FAIL", // 奥数 创建订单失败
    CHANGE_WEI_XIN_PAY_02_ORDER_STATUS:"CHANGE_WEI_XIN_PAY_02_ORDER_STATUS", // 奥数 改变订单状态

    FETCH_WEI_XIN_PAY_02_QUERY_ORDER_START:"FETCH_WEI_XIN_PAY_02_QUERY_ORDER_START", // 奥数 查询订单
    FETCH_WEI_XIN_PAY_02_QUERY_ORDER_SUCCESS:"FETCH_WEI_XIN_PAY_02_QUERY_ORDER_SUCCESS", // 奥数 查询订单成功
    FETCH_WEI_XIN_PAY_02_QUERY_ORDER_FAIL:"FETCH_WEI_XIN_PAY_02_QUERY_ORDER_FAIL", // 奥数 查询订单失败

    SAVE_WEI_XIN_PAY_02_SELECT_GOODS:"SAVE_WEI_XIN_PAY_02_SELECT_GOODS",//保存选择的商品

    SAVE_WEI_XIN_PAY_02_SELECT_GRADE:"SAVE_WEI_XIN_PAY_02_SELECT_GRADE",//保存选择的年级

    
};
/*
* 获取驯宠高手榜数据
* */
export const GET_TRAINING_PETS_MASTER_START = 'GET_TRAINING_PETS_MASTER_START';
export const TRAINING_PETS_MASTER_SUCCESS = 'TRAINING_PETS_MASTER_SUCCESS';
export const TRAINING_PETS_MASTER_FAILED = 'TRAINING_PETS_MASTER_FAILED';
/*
* 获取奥数组卷数据
* */
export const GET_MATH_PAPER = 'GET_MATH_PAPER';
export const MATH_PAPER_SUCCESS = 'MATH_PAPER_SUCCESS';
export const MATH_PAPER_FAILED = 'MATH_PAPER_FAILED';

/**
 * 成长页面发布消息页面获取数据
 */
export const GROWING_PUB_MSG ={
    FETCH_STATUS_LIST_START:"FETCH_STATUS_LIST_START", //获取谁能看见
    FETCH_STATUS_LIST_SUCCESS:"FETCH_STATUS_LIST_SUCCESS",
    FETCH_STATUS_LIST_FAIL:"FETCH_STATUS_LIST_FAIL",
    FETCH_LABEL_LIST_START:"FETCH_LABEL_LIST_START", //获取label标签
    FETCH_LABEL_LIST_SUCCESS:"FETCH_LABEL_LIST_SUCCESS",
    FETCH_LABEL_LIST_FAIL:"FETCH_LABEL_LIST_FAIL",
    FETCH_TYPE_LIST_START:"FETCH_TYPE_LIST_START", //获取type标签
    FETCH_TYPE_LIST_SUCCESS:"FETCH_TYPE_LIST_SUCCESS",
    FETCH_TYPE_LIST_FAIL:"FETCH_TYPE_LIST_FAIL",
    PUB_MSG_START:"PUB_MSG_START",
    PUB_MSG_SUCCESS:"PUB_MSG_SUCCESS",
    PUB_MSG_FAIL:"PUB_MSG_FAIL",
};

//获取自己的消息列表
export const GROWING_MYSELF_RECORD={
    FETCH_RECORD_LIST_START:"MYSELF_FETCH_RECORD_LIST_START", //获取列表
    FETCH_RECORD_LIST_SUCCESS:"MYSELF_FETCH_RECORD_LIST_SUCCESS",
    FETCH_RECORD_LIST_FAIL:"MYSELF_FETCH_RECORD_LIST_FAIL",
    SEND_PRAISE_START:"MYSELF_SEND_PRAISE_START", //点赞
    SEND_PRAISE_SUCCESS:"MYSELF_SEND_PRAISE_SUCCESS",
    SEND_PRAISE_FAIL:"MYSELF_SEND_PRAISE_FAIL",
    CANCEL_PRAISE_START:"MYSELF_CANCEL_PRAISE_START", //取消点赞
    CANCEL_PRAISE_SUCCESS:"MYSELF_CANCEL_PRAISE_SUCCESS",
    CANCEL_PRAISE_FAIL:"MYSELF_CANCEL_PRAISE_FAIL",
    SEND_FLOWER_START:"MYSELF_SEND_FLOWER_START", //送花
    SEND_FLOWER_SUCCESS:"MYSELF_SEND_FLOWER_SUCCESS",
    SEND_FLOWER_FAIL:"MYSELF_SEND_FLOWER_FAIL",
    CANCEL_FLOWER_START:"MYSELF_CANCEL_FLOWER_START", //取消送花
    CANCEL_FLOWER_SUCCESS:"MYSELF_CANCEL_FLOWER_SUCCESS",
    CANCEL_FLOWER_FAIL:"MYSELF_CANCEL_FLOWER_FAIL",
    DELETE_RECORD_START:"MYSELF_DELETE_RECORD_START", //删除消息
    DELETE_RECORD_SUCCESS:"MYSELF_DELETE_RECORD_SUCCESS",
    DELETE_RECORD_FAIL:"MYSELF_DELETE_RECORD_FAIL",
};

//获取同学消息列表
export const GROWING_CLASSMATE_RECORD = {
    FETCH_RECORD_LIST_START:"CLASSMATE_FETCH_RECORD_LIST_START", //获取列表
    FETCH_RECORD_LIST_SUCCESS:"CLASSMATE_FETCH_RECORD_LIST_SUCCESS",
    FETCH_RECORD_LIST_FAIL:"CLASSMATE_FETCH_RECORD_LIST_FAIL",
    SEND_PRAISE_START:"CLASSMATE_SEND_PRAISE_START", //点赞
    SEND_PRAISE_SUCCESS:"CLASSMATE_SEND_PRAISE_SUCCESS",
    SEND_PRAISE_FAIL:"CLASSMATE_SEND_PRAISE_FAIL",
    CANCEL_PRAISE_START:"CLASSMATE_CANCEL_PRAISE_START", //取消点赞
    CANCEL_PRAISE_SUCCESS:"CLASSMATE_CANCEL_PRAISE_SUCCESS",
    CANCEL_PRAISE_FAIL:"CLASSMATE_CANCEL_PRAISE_FAIL",
    SEND_FLOWER_START:"CLASSMATE_SEND_FLOWER_START", //送花
    SEND_FLOWER_SUCCESS:"CLASSMATE_SEND_FLOWER_SUCCESS",
    SEND_FLOWER_FAIL:"CLASSMATE_SEND_FLOWER_FAIL",
    CANCEL_FLOWER_START:"CLASSMATE_CANCEL_FLOWER_START", //取消送花
    CANCEL_FLOWER_SUCCESS:"CLASSMATE_CANCEL_FLOWER_SUCCESS",
    CANCEL_FLOWER_FAIL:"CLASSMATE_CANCEL_FLOWER_FAIL",
    FETCH_IMPEACH_REASON_LIST_START:"CLASSMATE_FETCH_IMPEACH_REASON_LIST_START", //获取举报理由列表
    FETCH_IMPEACH_REASON_LIST_SUCCESS:"CLASSMATE_FETCH_IMPEACH_REASON_LIST_SUCCESS",
    FETCH_IMPEACH_REASON_LIST_FAIL:"CLASSMATE_FETCH_IMPEACH_REASON_LIST_FAIL",
    IMPEACH_RECORD_START:"CLASSMATE_IMPEACH_RECORD_START", //举报消息
    IMPEACH_RECORD_SUCCESS:"CLASSMATE_IMPEACH_RECORD_SUCCESS",
    IMPEACH_RECORD_FAIL:"CLASSMATE_IMPEACH_RECORD_FAIL",
    CHANGE_SELECTED_CLASSMATE: "CHANGE_SELECTED_CLASSMATE", //改变选择的学生
};

//获取同学列表
export const GROWING_CLASSMATE_LIST = {
    FETCH_CLASSMATE_LIST_START:"FETCH_CLASSMATE_LIST_START", //获取同学列表
    FETCH_CLASSMATE_LIST_SUCCESS:"FETCH_CLASSMATE_LIST_SUCCESS",
    FETCH_CLASSMATE_LIST_FAIL:"FETCH_CLASSMATE_LIST_FAIL",
    CHANGE_SELECT_CLAZZ:"CHANGE_SELECT_CLAZZ", //改变选择班级
};

//获取朋友圈信息
export const GROWING_ONE_CLAZZ = {
    FETCH_ONE_CLAZZ_INFO_START:"FETCH_ONE_CLAZZ_INFO_START", //获取整个班级所有信息
    FETCH_ONE_CLAZZ_INFO_SUCCESS:"FETCH_ONE_CLAZZ_INFO_SUCCESS",
    FETCH_ONE_CLAZZ_INFO_FAIL:"FETCH_ONE_CLAZZ_INFO_FAIL",
    CHANGE_DISPLAY_SELECTED_CLAZZ:"CHANGE_DISPLAY_SELECTED_CLAZZ", //修改显示朋友圈消息的班级
    IMPEACH_RECORD_START:"IMPEACH_ONE_CLASSMATE_IN_CLAZZ_START",
    IMPEACH_RECORD_SUCCESS:"IMPEACH_ONE_CLASSMATE_IN_CLAZZ_SUCCESS",
    IMPEACH_RECORD_FAIL:"IMPEACH_ONE_CLASSMATE_IN_CLAZZ_FAIL",
    SEND_PRAISE_START:"ONE_CLAZZ_SEND_PRAISE_START", //点赞
    SEND_PRAISE_SUCCESS:"ONE_CLAZZ_SEND_PRAISE_SUCCESS",
    SEND_PRAISE_FAIL:"ONE_CLAZZ_SEND_PRAISE_FAIL",
    CANCEL_PRAISE_START:"ONE_CLAZZ_CANCEL_PRAISE_START", //取消点赞
    CANCEL_PRAISE_SUCCESS:"ONE_CLAZZ_CANCEL_PRAISE_SUCCESS",
    CANCEL_PRAISE_FAIL:"ONE_CLAZZ_CANCEL_PRAISE_FAIL",
    SEND_FLOWER_START:"ONE_CLAZZ_SEND_FLOWER_START", //送花
    SEND_FLOWER_SUCCESS:"ONE_CLAZZ_SEND_FLOWER_SUCCESS",
    SEND_FLOWER_FAIL:"ONE_CLAZZ_SEND_FLOWER_FAIL",
    CANCEL_FLOWER_START:"ONE_CLAZZ_CANCEL_FLOWER_START", //取消送花
    CANCEL_FLOWER_SUCCESS:"ONE_CLAZZ_CANCEL_FLOWER_SUCCESS",
    CANCEL_FLOWER_FAIL:"ONE_CLAZZ_CANCEL_FLOWER_FAIL",
    DELETE_RECORD_START:"ONE_CLAZZ_DELETE_RECORD_START", //删除
    DELETE_RECORD_SUCCESS:"ONE_CLAZZ_DELETE_RECORD_SUCCESS",
    DELETE_RECORD_FAIL:"ONE_CLAZZ_DELETE_RECORD_FAIL",
};

//积分、经验
export const REWARD_INFO = {
    GET_USER_REWARD_BASE: 'GET_USER_REWARD_BASE',//用户积分和经验信息
    GET_USER_REWARD_BASE_FAIL: 'GET_USER_REWARD_BASE_FAIL',//用户积分和经验信息
    GET_USER_REWARD_BASE_START: 'GET_USER_REWARD_BASE_START',//用户积分和经验信息
    GET_USER_REWARD_BASE_SUCCESS: 'GET_USER_REWARD_BASE_SUCCESS',//用户积分和经验信息
    CHANGE_USER_REWARD_BASE:'CHANGE_USER_REWARD_BASE',//修改用户积分和经验信息

    UPDATE_USER_REWARD_BASE:'UPDATE_USER_REWARD_BASE',//更新用户积分和经验信息
    UPDATE_USER_REWARD_BASE_START:'UPDATE_USER_REWARD_BASE_START',//开始更新用户积分和经验信息
    UPDATE_USER_REWARD_BASE_SUCCESS:'UPDATE_USER_REWARD_BASE_SUCCESS',//更新用户积分和经验信息成
    UPDATE_USER_REWARD_BASE_FAIL:'UPDATE_USER_REWARD_BASE_FAIL',//更新用户积分和经验信息失败

    FETCH_LEVEL_NAME_LIST: "FETCH_LEVEL_NAME_LIST",//获取称号列表信息
    FETCH_LEVEL_NAME_LIST_START: "FETCH_LEVEL_NAME_LIST_START",//开始称号列表
    FETCH_LEVEL_NAME_LIST_SUCCESS: "FETCH_LEVEL_NAME_LIST_SUCCESS",//称号列表成功
    FETCH_LEVEL_NAME_LIST_FAIL: "FETCH_LEVEL_NAME_LIST_FAIL" //称号列表失败


};

//作业报告
export const WORK_REPORT = {
  GET_WORK_REPORT_INFO:'GET_WORK_REPORT_INFO',//获取是作业报告详情
  GET_WORK_REPORT_INFO_FAIL:'GET_WORK_REPORT_INFO_FAIL',//获取是作业报告详情开始
  GET_WORK_REPORT_INFO_START:'GET_WORK_REPORT_INFO_START',//获取是作业报告详情成功
  GET_WORK_REPORT_INFO_SUCCESS:'GET_WORK_REPORT_INFO_SUCCESS',//获取是作业报告详情失败

  CHANGE_WORK_REPORT_PAPER_INFO:"CHANGE_WORK_REPORT_PAPER_INFO" ,//修改当前选择报告的试卷信息

  SAVE_WORK_QUES_RECORD:'SAVE_WORK_QUES_RECORD', //保存试卷中每个考点，对应的题
  SAVE_SELECT_WORK_KNOWLEDGE:'SAVE_SELECT_WORK_KNOWLEDGE',//保存选择的知识点信息

  CHANGE_DIAGNOSE_DIALOG_FLAG:'CHANGE_DIAGNOSE_DIALOG_FLAG',//首页诊断广告显示状态
};

//训练营
export const DIAGNOSE_CAMP = {
    GET_CAMP_GOODS_LIST:'GET_CAMP_GOODS_LIST',
    GET_CAMP_GOODS_LIST_FAIL:'GET_CAMP_GOODS_LIST_FAIL',
    GET_CAMP_GOODS_LIST_START:'GET_CAMP_GOODS_LIST_START',
    GET_CAMP_GOODS_LIST_SUCCESS:'GET_CAMP_GOODS_LIST_SUCCESS'
};

export const SMART_TRAINING_CAMP = {
    GET_SMART_TRAINING_CAMP_START:'GET_SMART_TRAINING_CAMP_START',  //获取学霸训练营数据开始
    GET_SMART_TRAINING_CAMP_SUCCESS:'GET_SMART_TRAINING_CAMP_SUCCESS',  //获取学霸训练营数据成功
    GET_SMART_TRAINING_CAMP_FAIL:'GET_SMART_TRAINING_CAMP_FAIL',  //获取学霸训练营数据失败
    GET_SMART_TRAINING_CAMP_REWARD_START:'GET_SMART_TRAINING_CAMP_REWARD_START',  //获取学霸训练营奖励开始
    GET_SMART_TRAINING_CAMP_REWARD_SUCCESS:'GET_SMART_TRAINING_CAMP_REWARD_SUCCESS',  //获取学霸训练营奖励成功
    GET_SMART_TRAINING_CAMP_REWARD_FAIL:'GET_SMART_TRAINING_CAMP_REWARD_FAIL',  //获取学霸训练营奖励失败
    CHANGE_SMART_TRAINING_CAMP_INFO:'CHANGE_SMART_TRAINING_CAMP_INFO',  //修改学霸训练营数据
};

//宠物蛋
export const PET_INFO = {
    FETCH_PET_INFO_SUCCESS:"FETCH_PET_INFO_SUCCESS",
    HATCH_FIRST_PET:"HATCH_FIRST_PET",//孵化第一只宠物成功
    HATCH_PET_SUCCESS:'HATCH_PET_SUCCESS', //孵化宠物成功
    BUY_PET_FOOD_SUCCESS:'BUY_PET_FOOD_SUCCESS', //能量兑换宠物食物成功
    FEED_PET_SUCCESS:'FEED_PET_SUCCESS', //成功喂养宠物
    GET_PET_GOODS_SUCCESS:'GET_PET_GOODS_SUCCESS', //领取食物奖励
    CHANGE_SHOW_AD_AUTO_FLAG:"CHANGE_SHOW_AD_AUTO_FLAG",
    CHANGE_PET_FIRST_GUIDE_FLAG:"CHANGE_PET_FIRST_GUIDE_FLAG",
    CHANGE_CAN_GET_REWARD_FLAG:'CHANGE_CAN_GET_REWARD_FLAG',
    CHANGE_SHARE_SUCCESS_FLAG:'CHANGE_SHARE_SUCCESS_FLAG',

};
//口算答题时间
export const ORAL_CALCULATION = {
    UPDATE_ORAL_CALCULATION_LIMITTIME:'UPDATE_ORAL_CALCULATION_LIMITTIME', //更新计时
    UPDATE_ORAL_CALCULATION_TIMER:'UPDATE_ORAL_CALCULATION_TIMER', //更新计时器
    DELETE_ORAL_CALCULATION_LIMITTIM:'DELETE_ORAL_CALCULATION_LIMITTIM',//删除计时
};
//期末测评答题时间
export const FINAL_ACCESS = {
    UPDATE_FINAL_ACCESS_LIMITTIME:'UPDATE_FINAL_ACCESS_LIMITTIME', //更新计时
    UPDATE_FINAL_ACCESS_TIMER:'UPDATE_FINAL_ACCESS_TIMER', //更新计时器
    DELETE_FINAL_ACCESS_LIMITTIM:'DELETE_FINAL_ACCESS_LIMITTIM',//删除计时
};
export const COUNT_DOWN_VIP_INCREASE_SCORE_COUNTS = 'COUNT_DOWN_VIP_INCREASE_SCORE_COUNTS'; //诊断提分，考点特权数减1
