var path = require("path");
var moduleEntryMap = {
    //学生端
    m_final_sprint: path.join(__dirname, '../', "src/student/modules/m_final_sprint/scripts", '/index.js'),
    m_final_sprint_payment: path.join(__dirname, '../', "src/student/modules/m_final_sprint_payment/scripts", '/index.js'),
    m_final_sprint_question: path.join(__dirname, '../', "src/student/modules/m_final_sprint_question/scripts", '/index.js'),
    m_game_map: path.join(__dirname, '../', "src/student/modules/m_game_map/scripts", '/index.js'),
    m_math_game: path.join(__dirname, '../', "src/student/modules/m_math_game/scripts", '/index.js'),
    m_compute: path.join(__dirname, '../', "src/student/modules/m_compute/scripts", '/index.js'),
    m_user_auth: path.join(__dirname, '../', "src/student/modules/m_user_auth/scripts", '/index.js'),
    m_diagnose:path.join(__dirname, '../', "src/student/modules/m_diagnose/scripts", '/index.js'),
    // gameMap: path.join(__dirname, '../', "src/modules/game_map/scripts", '/index.js'),
    m_home: path.join(__dirname, '../', "src/student/modules/m_home", '/index.js'),
    oral_calculation: path.join(__dirname, '../', "src/student/modules/m_oral_calculation", '/index.js'),
    m_reward: path.join(__dirname, '../', "src/student/modules/m_reward/scripts", '/index.js'),
    m_diagnose_pk: path.join(__dirname, '../', "src/student/modules/m_diagnose_pk", '/index.js'),
    m_me_classes: path.join(__dirname, '../', "src/student/modules/m_me_classes/scripts", '/index.js'),
    m_global: path.join(__dirname, '../', "src/student/modules/m_global/scripts", '/index.js'),
    m_me: path.join(__dirname, '../', "src/student/modules/m_me/scripts", '/index.js'),
    student: path.join(__dirname, '../', "src/student/modules/m_boot/scripts", '/index.js'),
    m_diagnose_payment: path.join(__dirname, '../', "src/student/modules/m_diagnose_payment/scripts", '/index.js'),
    m_increase_score_payment: path.join(__dirname, '../', "src/student/modules/m_increaseScore_payment/scripts", '/index.js'),
    m_pet_page: path.join(__dirname, '../', "src/student/modules/m_pet_page/scripts", '/index.js'),
    m_xly: path.join(__dirname, '../', "src/student/modules/m_xly/scripts", '/index.js'),
    m_olympic_math_home: path.join(__dirname, '../', "src/student/modules/m_olympic_math_home/scripts", '/index.js'),
    m_work: path.join(__dirname, '../', "src/student/modules/m_work/scripts", '/index.js'),
    m_holiday_work: path.join(__dirname, '../', "src/student/modules/m_holiday_work/scripts", '/index.js'),
    m_question_every_day: path.join(__dirname, '../', "src/student/modules/m_question_every_day/scripts", '/index.js'),
    m_winter_camp: path.join(__dirname, '../', "src/student/modules/m_winter_camp/scripts", '/index.js'),
    m_improve: path.join(__dirname, '../', "src/student/modules/m_improve/scripts", '/index.js'),
    m_olympic_math_microlecture: path.join(__dirname, '../', "src/student/modules/m_olympic_math_microlecture/scripts", '/index.js'),
    m_live: path.join(__dirname, '../', "src/student/modules/m_live/scripts", '/index.js'),
    m_online_teaching: path.join(__dirname, '../', "src/student/modules/m_online_teaching", '/index.js'),


    //教师端
    teacher: path.join(__dirname, '../', "src/teacher_old/modules/t_boot/scripts", '/bootstrap.js'),
    t_global: path.join(__dirname, '../', "src/teacher_old/modules/t_global/scripts", '/index.js'),
    t_home: path.join(__dirname, '../', "src/teacher_old/modules/t_home/scripts", '/index.js'),
    t_home_teaching_work: path.join(__dirname, '../', "src/teacher_old/modules/t_home_teaching_work/scripts", '/index.js'),
    t_work_publish1:path.join(__dirname, '../', "src/teacher_old/modules/t_work_publish1/scripts", '/index.js'),
    t_work_publish2:path.join(__dirname, '../', "src/teacher_old/modules/t_work_publish2/scripts", '/index.js'),
    t_work_publish3:path.join(__dirname, '../', "src/teacher_old/modules/t_work_publish3/scripts", '/index.js'),

    t_classes: path.join(__dirname, '../', "src/teacher_old/modules/t_classes/scripts", '/index.js'),
    t_credits_store: path.join(__dirname, '../', "src/teacher_old/modules/t_credits_store/scripts", '/index.js'),
    t_me: path.join(__dirname, '../', "src/teacher_old/modules/t_me/scripts", '/index.js'),
    t_work_publish4: path.join(__dirname, '../', "src/teacher_old/modules/t_work_publish4/scripts", '/index.js'),
    t_teacher_group: path.join(__dirname, '../', "src/teacher_old/modules/t_teacher_group/scripts", '/index.js'),
    t_game: path.join(__dirname, '../', "src/teacher_old/modules/t_game/scripts", '/index.js'),
    t_compute: path.join(__dirname, '../', "src/teacher_old/modules/t_compute/scripts", '/index.js'),
    t_diagnose: path.join(__dirname, '../', "src/teacher_old/modules/t_diagnose/scripts", '/index.js'),
    t_user_auth: path.join(__dirname, '../', "src/teacher_old/modules/t_user_auth/scripts", '/index.js'),
    t_area_evaluation: path.join(__dirname, '../', "src/teacher_old/modules/t_area_evaluation/scripts", '/index.js'),
    t_personal_qb: path.join(__dirname, '../', "src/teacher_old/modules/t_personal_qb/scripts", '/index.js'),
    t_online_teaching: path.join(__dirname, '../', "src/teacher_old/modules/t_online_teaching", '/index.js'),
    
};
module.exports = moduleEntryMap;