/**
 * Created by qiyuexi on 2017/12/8.
 */
export const SELECT_COURSE ='SELECT_COURSE_SUCCESS';//设置选择的课程
export const SELECT_MY_COURSE ='SELECT_MY_COURSE_SUCCESS';//设置选择的报名的课程
export const SET_WATCH_VIDEO_FLAG ='SET_WATCH_VIDEO_FLAG';//设置观看回放视频的弹窗提示flag
export const SET_CURRENT_COURSE_FLAG ='SET_CURRENT_COURSE_FLAG';//设置每天重新计算默认一次公开课的标识
export const LIVE_GOODS={ //支付商品

    LIVE_GOODS_CREATE_ORDER_START:'LIVE_GOODS_CREATE_ORDER_START', //创建订单
    LIVE_GOODS_CREATE_ORDER_SUCCESS:'LIVE_GOODS_CREATE_ORDER_SUCCESS',
    LIVE_GOODS_CREATE_ORDER_FAIL:'LIVE_GOODS_CREATE_ORDER_FAIL',
    CHANGE_LIVE_GOODS_CREATE_ORDER_STATUS:'CHANGE_LIVE_GOODS_CREATE_ORDER_STATUS',//修改订单

    LIVE_GOODS_QUERY_ORDER_INFO_START:'LIVE_GOODS_QUERY_ORDER_INFO_START', //查询订单信息
    LIVE_GOODS_QUERY_ORDER_INFO_SUCCESS:'LIVE_GOODS_QUERY_ORDER_INFO_SUCCESS',
    LIVE_GOODS_QUERY_ORDER_INFO_FAIL:'LIVE_GOODS_QUERY_ORDER_INFO_FAIL',
};
