
//砍价
export const BARGAIN={
    FETCH_BARGAIN_DETAIL_START:"FETCH_BARGAIN_DETAIL_START",
    FETCH_BARGAIN_DETAIL_SUCCESS:"FETCH_BARGAIN_DETAIL_SUCCESS",
    FETCH_BARGAIN_DETAIL_FAIL:"FETCH_BARGAIN_DETAIL_FAIL"
}
