/**
 * Created by WW on 2018/1/5.
 */
export const HOLIDAY_WORK = {
    //获取假期作业列表
    FETCH_HOLIDAY_WORK_LIST_START:'FETCH_HOLIDAY_WORK_LIST_START',
    FETCH_HOLIDAY_WORK_LIST_SUCCESS:'FETCH_HOLIDAY_WORK_LIST_SUCCESS',
    FETCH_HOLIDAY_WORK_LIST_FAIL:'FETCH_HOLIDAY_WORK_LIST_FAIL',
};
