/**
 * Created by qiyuexi on 2017/12/8.
 */
export const PAPER_LIST = {
    FETCH_PAPER_LIST_START: "FETCH_PAPER_LIST_START",//获取试卷开始
    FETCH_PAPER_LIST_SUCCESS: "FETCH_PAPER_LIST_SUCCESS",//获取试卷成功
    FETCH_PAPER_LIST_FAIL: "FETCH_PAPER_LIST_FAIL",//获取试卷失败

    SELECT_PAPER_BY_WEEK:"SELECT_SPRINT_BY_WEEK",//设置当前所选择周的试卷
    // IS_CLICK_SECOND_BTN:"IS_CLICK_SECOND_BTN",//是否点击进入过了第二步
};
export const STATUS_LIST = {
    FETCH_STATUS_LIST_START: "FETCH_STATUS_LIST_START",//获取试卷状态开始
    FETCH_STATUS_LIST_SUCCESS: "FETCH_STATUS_LIST_SUCCESS",//获取状态成功
    FETCH_STATUS_LIST_FAIL: "FETCH_STATUS_LIST_FAIL",//获取状态失败
};
export const SPRINT_INFO = {
    FETCH_SPRINT_INFO_START: "FETCH_SPRINT_INFO_START",//获取期末冲刺相关信息开始
    FETCH_SPRINT_INFO_SUCCESS: "FETCH_SPRINT_INFO_SUCCESS",//获取期末冲刺相关信息成功
    FETCH_SPRINT_INFO_FAIL: "FETCH_SPRINT_INFO_FAIL",//获取期末冲刺相关信息失败
};
export const FIRST_COME_IN="FIRST_COME_IN";//是否是第一次进入这个任务

export const FINAL_SPRINT_GOODS={ //支付商品
    FETCH_SPRINT_GOODS_LIST_START:'FETCH_SPRINT_GOODS_LIST_START',//获取商品列表
    FETCH_SPRINT_GOODS_LIST_SUCCESS:'FETCH_SPRINT_GOODS_LIST_SUCCESS',
    FETCH_SPRINT_GOODS_LIST_FAIL:'FETCH_SPRINT_GOODS_LIST_FAIL',
    SELECT_SPRINT_GOODS:'SELECT_SPRINT_GOODS',//选择的商品

    SPRINT_GOODS_CREATE_ORDER_START:'SPRINT_GOODS_CREATE_ORDER_START', //创建订单
    SPRINT_GOODS_CREATE_ORDER_SUCCESS:'SPRINT_GOODS_CREATE_ORDER_SUCCESS',
    SPRINT_GOODS_CREATE_ORDER_FAIL:'SPRINT_GOODS_CREATE_ORDER_FAIL',
    CHANGE_SPRINT_GOODS_CREATE_ORDER_STATUS:'CHANGE_SPRINT_GOODS_CREATE_ORDER_STATUS',//修改订单

    SPRINT_GOODS_QUERY_ORDER_INFO_START:'SPRINT_GOODS_QUERY_ORDER_INFO_START', //查询订单信息
    SPRINT_GOODS_QUERY_ORDER_INFO_SUCCESS:'SPRINT_GOODS_QUERY_ORDER_INFO_SUCCESS',
    SPRINT_GOODS_QUERY_ORDER_INFO_FAIL:'SPRINT_GOODS_QUERY_ORDER_INFO_FAIL',
};